# Generated by Django 3.2.13 on 2022-05-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_default_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_phone',
            new_name='default_phone_number',
        ),
    ]
