# Generated by Django 3.2.13 on 2022-05-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='surname',
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='John Doe', max_length=60),
        ),
    ]
