# Generated by Django 3.2.13 on 2022-05-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
