# Generated by Django 3.2.13 on 2022-05-03 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('courses', '0004_auto_20220503_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
