# Generated by Django 3.2.13 on 2022-06-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
