# Generated by Django 3.2.13 on 2022-06-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sku',
        ),
    ]
