# Generated by Django 3.2.13 on 2022-05-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='location',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
