# Generated by Django 3.2.13 on 2022-05-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20220523_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='closing_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
